/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerDashboardRouteImport } from './routes/customer.dashboard'
import { Route as AdminQueriesRouteImport } from './routes/admin.queries'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminChangeCredentialsRouteImport } from './routes/admin.change-credentials'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin.projects.index'
import { Route as AdminNewslettersIndexRouteImport } from './routes/admin.newsletters.index'
import { Route as AdminNewsIndexRouteImport } from './routes/admin.news.index'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin.customers.index'
import { Route as CustomerProjectIdRouteImport } from './routes/customer.project.$id'
import { Route as AdminProjectsIdRouteImport } from './routes/admin.projects.$id'
import { Route as AdminNewslettersCreateRouteImport } from './routes/admin.newsletters.create'
import { Route as AdminNewsCreateRouteImport } from './routes/admin.news.create'
import { Route as AdminCustomersCreateRouteImport } from './routes/admin.customers.create'
import { Route as AdminNewslettersIdEditRouteImport } from './routes/admin.newsletters.$id.edit'
import { Route as AdminNewsIdEditRouteImport } from './routes/admin.news.$id.edit'
import { Route as AdminCustomersIdEditRouteImport } from './routes/admin.customers.$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDashboardRoute = CustomerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CustomerRoute,
} as any)
const AdminQueriesRoute = AdminQueriesRouteImport.update({
  id: '/queries',
  path: '/queries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChangeCredentialsRoute = AdminChangeCredentialsRouteImport.update({
  id: '/change-credentials',
  path: '/change-credentials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewslettersIndexRoute = AdminNewslettersIndexRouteImport.update({
  id: '/newsletters/',
  path: '/newsletters/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsIndexRoute = AdminNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AdminRoute,
} as any)
const CustomerProjectIdRoute = CustomerProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => CustomerRoute,
} as any)
const AdminProjectsIdRoute = AdminProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewslettersCreateRoute = AdminNewslettersCreateRouteImport.update({
  id: '/newsletters/create',
  path: '/newsletters/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsCreateRoute = AdminNewsCreateRouteImport.update({
  id: '/news/create',
  path: '/news/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersCreateRoute = AdminCustomersCreateRouteImport.update({
  id: '/customers/create',
  path: '/customers/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewslettersIdEditRoute = AdminNewslettersIdEditRouteImport.update({
  id: '/newsletters/$id/edit',
  path: '/newsletters/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsIdEditRoute = AdminNewsIdEditRouteImport.update({
  id: '/news/$id/edit',
  path: '/news/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersIdEditRoute = AdminCustomersIdEditRouteImport.update({
  id: '/customers/$id/edit',
  path: '/customers/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/change-credentials': typeof AdminChangeCredentialsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/queries': typeof AdminQueriesRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/admin/customers/create': typeof AdminCustomersCreateRoute
  '/admin/news/create': typeof AdminNewsCreateRoute
  '/admin/newsletters/create': typeof AdminNewslettersCreateRoute
  '/admin/projects/$id': typeof AdminProjectsIdRoute
  '/customer/project/$id': typeof CustomerProjectIdRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/news/': typeof AdminNewsIndexRoute
  '/admin/newsletters/': typeof AdminNewslettersIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/customers/$id/edit': typeof AdminCustomersIdEditRoute
  '/admin/news/$id/edit': typeof AdminNewsIdEditRoute
  '/admin/newsletters/$id/edit': typeof AdminNewslettersIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/change-credentials': typeof AdminChangeCredentialsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/queries': typeof AdminQueriesRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/admin/customers/create': typeof AdminCustomersCreateRoute
  '/admin/news/create': typeof AdminNewsCreateRoute
  '/admin/newsletters/create': typeof AdminNewslettersCreateRoute
  '/admin/projects/$id': typeof AdminProjectsIdRoute
  '/customer/project/$id': typeof CustomerProjectIdRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/news': typeof AdminNewsIndexRoute
  '/admin/newsletters': typeof AdminNewslettersIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/customers/$id/edit': typeof AdminCustomersIdEditRoute
  '/admin/news/$id/edit': typeof AdminNewsIdEditRoute
  '/admin/newsletters/$id/edit': typeof AdminNewslettersIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/change-credentials': typeof AdminChangeCredentialsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/queries': typeof AdminQueriesRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/admin/customers/create': typeof AdminCustomersCreateRoute
  '/admin/news/create': typeof AdminNewsCreateRoute
  '/admin/newsletters/create': typeof AdminNewslettersCreateRoute
  '/admin/projects/$id': typeof AdminProjectsIdRoute
  '/customer/project/$id': typeof CustomerProjectIdRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/news/': typeof AdminNewsIndexRoute
  '/admin/newsletters/': typeof AdminNewslettersIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/customers/$id/edit': typeof AdminCustomersIdEditRoute
  '/admin/news/$id/edit': typeof AdminNewsIdEditRoute
  '/admin/newsletters/$id/edit': typeof AdminNewslettersIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/customer'
    | '/login'
    | '/admin/change-credentials'
    | '/admin/dashboard'
    | '/admin/queries'
    | '/customer/dashboard'
    | '/admin/customers/create'
    | '/admin/news/create'
    | '/admin/newsletters/create'
    | '/admin/projects/$id'
    | '/customer/project/$id'
    | '/admin/customers/'
    | '/admin/news/'
    | '/admin/newsletters/'
    | '/admin/projects/'
    | '/admin/customers/$id/edit'
    | '/admin/news/$id/edit'
    | '/admin/newsletters/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/customer'
    | '/login'
    | '/admin/change-credentials'
    | '/admin/dashboard'
    | '/admin/queries'
    | '/customer/dashboard'
    | '/admin/customers/create'
    | '/admin/news/create'
    | '/admin/newsletters/create'
    | '/admin/projects/$id'
    | '/customer/project/$id'
    | '/admin/customers'
    | '/admin/news'
    | '/admin/newsletters'
    | '/admin/projects'
    | '/admin/customers/$id/edit'
    | '/admin/news/$id/edit'
    | '/admin/newsletters/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/customer'
    | '/login'
    | '/admin/change-credentials'
    | '/admin/dashboard'
    | '/admin/queries'
    | '/customer/dashboard'
    | '/admin/customers/create'
    | '/admin/news/create'
    | '/admin/newsletters/create'
    | '/admin/projects/$id'
    | '/customer/project/$id'
    | '/admin/customers/'
    | '/admin/news/'
    | '/admin/newsletters/'
    | '/admin/projects/'
    | '/admin/customers/$id/edit'
    | '/admin/news/$id/edit'
    | '/admin/newsletters/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CustomerRoute: typeof CustomerRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard': {
      id: '/customer/dashboard'
      path: '/dashboard'
      fullPath: '/customer/dashboard'
      preLoaderRoute: typeof CustomerDashboardRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/admin/queries': {
      id: '/admin/queries'
      path: '/queries'
      fullPath: '/admin/queries'
      preLoaderRoute: typeof AdminQueriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/change-credentials': {
      id: '/admin/change-credentials'
      path: '/change-credentials'
      fullPath: '/admin/change-credentials'
      preLoaderRoute: typeof AdminChangeCredentialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletters/': {
      id: '/admin/newsletters/'
      path: '/newsletters'
      fullPath: '/admin/newsletters/'
      preLoaderRoute: typeof AdminNewslettersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news/': {
      id: '/admin/news/'
      path: '/news'
      fullPath: '/admin/news/'
      preLoaderRoute: typeof AdminNewsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/customer/project/$id': {
      id: '/customer/project/$id'
      path: '/project/$id'
      fullPath: '/customer/project/$id'
      preLoaderRoute: typeof CustomerProjectIdRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/admin/projects/$id': {
      id: '/admin/projects/$id'
      path: '/projects/$id'
      fullPath: '/admin/projects/$id'
      preLoaderRoute: typeof AdminProjectsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletters/create': {
      id: '/admin/newsletters/create'
      path: '/newsletters/create'
      fullPath: '/admin/newsletters/create'
      preLoaderRoute: typeof AdminNewslettersCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news/create': {
      id: '/admin/news/create'
      path: '/news/create'
      fullPath: '/admin/news/create'
      preLoaderRoute: typeof AdminNewsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/create': {
      id: '/admin/customers/create'
      path: '/customers/create'
      fullPath: '/admin/customers/create'
      preLoaderRoute: typeof AdminCustomersCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletters/$id/edit': {
      id: '/admin/newsletters/$id/edit'
      path: '/newsletters/$id/edit'
      fullPath: '/admin/newsletters/$id/edit'
      preLoaderRoute: typeof AdminNewslettersIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news/$id/edit': {
      id: '/admin/news/$id/edit'
      path: '/news/$id/edit'
      fullPath: '/admin/news/$id/edit'
      preLoaderRoute: typeof AdminNewsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/$id/edit': {
      id: '/admin/customers/$id/edit'
      path: '/customers/$id/edit'
      fullPath: '/admin/customers/$id/edit'
      preLoaderRoute: typeof AdminCustomersIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminChangeCredentialsRoute: typeof AdminChangeCredentialsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminQueriesRoute: typeof AdminQueriesRoute
  AdminCustomersCreateRoute: typeof AdminCustomersCreateRoute
  AdminNewsCreateRoute: typeof AdminNewsCreateRoute
  AdminNewslettersCreateRoute: typeof AdminNewslettersCreateRoute
  AdminProjectsIdRoute: typeof AdminProjectsIdRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminNewsIndexRoute: typeof AdminNewsIndexRoute
  AdminNewslettersIndexRoute: typeof AdminNewslettersIndexRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
  AdminCustomersIdEditRoute: typeof AdminCustomersIdEditRoute
  AdminNewsIdEditRoute: typeof AdminNewsIdEditRoute
  AdminNewslettersIdEditRoute: typeof AdminNewslettersIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminChangeCredentialsRoute: AdminChangeCredentialsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminQueriesRoute: AdminQueriesRoute,
  AdminCustomersCreateRoute: AdminCustomersCreateRoute,
  AdminNewsCreateRoute: AdminNewsCreateRoute,
  AdminNewslettersCreateRoute: AdminNewslettersCreateRoute,
  AdminProjectsIdRoute: AdminProjectsIdRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminNewsIndexRoute: AdminNewsIndexRoute,
  AdminNewslettersIndexRoute: AdminNewslettersIndexRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
  AdminCustomersIdEditRoute: AdminCustomersIdEditRoute,
  AdminNewsIdEditRoute: AdminNewsIdEditRoute,
  AdminNewslettersIdEditRoute: AdminNewslettersIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CustomerRouteChildren {
  CustomerDashboardRoute: typeof CustomerDashboardRoute
  CustomerProjectIdRoute: typeof CustomerProjectIdRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerDashboardRoute: CustomerDashboardRoute,
  CustomerProjectIdRoute: CustomerProjectIdRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CustomerRoute: CustomerRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
